version: '3'
services: 
  web:
    container_name: web-api
    build: .
    command: npm run start
    volumes:
      - .:/usr/app/
    environment:
      - PORT=8080
      - HOST=0.0.0.0
      - PROJECT_DIR=/usr/app
      - NODE_ENV=development
      - LOG_LEVEL=debug
    ports:
      - "8080:8080"
